<?php

use Illuminate\Database\Seeder;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('languages')->insert([
           ['language' => 'English'],
            ['language' => 'French'],
            ['language' => 'Arabic'],
            ['language' => 'Mandarin'],
            ['language' => 'Spanish'],
            ['language' => 'Hindi'],
            ['language' => 'Portuguese'],
            ['language' => 'Bengali'],
            ['language' => 'Russian'],
            ['language' => 'Japanese'],
            ['language' => 'Punjabi'],
            ['language' => 'German'],
            ['language' => 'Javanese'],
            ['language' => 'Wu'],
            ['language' => 'Malay'],
            ['language' => 'Telugu'],
            ['language' => 'Vietnamese'],
            ['language' => 'Korean'],
            ['language' => 'Marathi'],
            ['language' => 'Tamil'],
            ['language' => 'Urdu'],
            ['language' => 'Turkish'],
            ['language' => 'Italian'],
            ['language' => 'Yue'],
            ['language' => 'Thai'],
            ['language' => 'Gujarati'],
            ['language' => 'Jin'],
            ['language' => 'Southern Min'],
            ['language' => 'Persian'],
            ['language' => 'Polish'],
            ['language' => 'Pashto'],
            ['language' => 'Kannada'],
            ['language' => 'Xiang'],
            ['language' => 'Malayalam'],
            ['language' => 'Sundanese'],
            ['language' => 'Hausa'],
            ['language' => 'Odia'],
            ['language' => 'Burmese'],
            ['language' => 'Hakka'],
            ['language' => 'Ukrainian'],
            ['language' => 'Bhojpuri'],
            ['language' => 'Tagalog'],
            ['language' => 'Yoruba'],
            ['language' => 'Maithili'],
            ['language' => 'Uzbek'],
            ['language' => 'Sindhi'],
            ['language' => 'Amharic'],
            ['language' => 'Fula'],
            ['language' => 'Romanian'],
            ['language' => 'Oromo'],
            ['language' => 'Igbo'],
            ['language' => 'Azerbaijani'],
            ['language' => 'Awadhi'],
            ['language' => 'Gan'],
            ['language' => 'Cebuano'],
            ['language' => 'Dutch'],
            ['language' => 'Kurdish'],
            ['language' => 'Serbo-Croatian'],
            ['language' => 'Malagasy'],
            ['language' => 'Saraiki'],
            ['language' => 'Nepali'],
            ['language' => 'Sinhalese'],
            ['language' => 'Chittagonian'],
            ['language' => 'Zhuang'],
            ['language' => 'Khmer'],
            ['language' => 'Turkmen'],
            ['language' => 'Assamese'],
            ['language' => 'Madurese'],
            ['language' => 'Somali'],
            ['language' => 'Marwari'],
            ['language' => 'Magahi'],
            ['language' => 'Haryanvi'],
            ['language' => 'Hungarian'],
            ['language' => 'Chhattisgarhi'],
            ['language' => 'Greek'],
            ['language' => 'Chewa'],
            ['language' => 'Deccan'],
            ['language' => 'Akan'],
            ['language' => 'Kazakh'],
            ['language' => 'Northern Min'],
            ['language' => 'Sylheti'],
            ['language' => 'Zulu'],
            ['language' => 'Czech'],
            ['language' => 'Kinyarwanda'],
            ['language' => 'Dhundhari'],
            ['language' => 'Haitian Creole'],
            ['language' => 'Eastern Min'],
            ['language' => 'Ilocano'],
            ['language' => 'Quechua'],
            ['language' => 'Kirundi'],
            ['language' => 'Swedish'],
            ['language' => 'Hmong'],
            ['language' => 'Shona'],
            ['language' => 'Uyghur'],
            ['language' => 'Hiligaynon/Ilonggo'],
            ['language' => 'Mossi'],
            ['language' => 'Xhosa'],
            ['language' => 'Belarusian'],
            ['language' => 'Balochi'],
            ['language' => 'Konkani'],
        ]);
    }
}
