stages:
  - test


dusk:
  stage: test
  image: chilio/laravel-dusk-ci:stable

  variables:
    # MYSQL_ROOT_PASSWORD: root
 #   MYSQL_PASSWORD: root

    DB_CONNECTION: memory
    DB_DATABASE:   eduplay
    DB_USERNAME:  root
    DB_PASSWORD:  root
  services:
    - name: mysql:5.7

  script:
    - cp .env.mhdfordusk .env
    - composer install
    - configure-laravel
    - start-nginx-ci-project
    - composer test
    - php artisan dusk:install
    - php artisan dusk
  artifacts:
    paths:
      - tests/Browser/screenshots
